CREATE TABLE [dbo].[ETAPA]
(
[IDETA] [int] NOT NULL IDENTITY(1, 1),
[NOMETA] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ETAPA] ADD CONSTRAINT [ETAPA_pk] PRIMARY KEY CLUSTERED ([IDETA]) ON [PRIMARY]
GO
