CREATE TABLE [dbo].[MARCA]
(
[IDMAR] [int] NOT NULL IDENTITY(1, 1),
[NOMMAR] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTMAR] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MARCA] ADD CONSTRAINT [MARCA_pk] PRIMARY KEY CLUSTERED ([IDMAR]) ON [PRIMARY]
GO
