CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[CANTVENDET] [int] NOT NULL,
[IDVEN] [int] NOT NULL,
[CODPRO] [char] (6) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_pk] PRIMARY KEY CLUSTERED ([IDVENDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([CODPRO]) REFERENCES [dbo].[PRODUCTO] ([CODPRO])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_VENTA] FOREIGN KEY ([IDVEN]) REFERENCES [dbo].[VENTA] ([IDVEN])
GO
