CREATE TABLE [dbo].[CATEGORIA]
(
[IDCAT] [int] NOT NULL IDENTITY(1, 1),
[NOMCAT] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTCAT] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD CONSTRAINT [CATEGORIA_pk] PRIMARY KEY CLUSTERED ([IDCAT]) ON [PRIMARY]
GO
