CREATE TABLE [dbo].[PRODUCTO]
(
[CODPRO] [char] (6) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMPRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PRECPRO] [decimal] (8, 2) NOT NULL,
[STOCKPRO] [int] NOT NULL,
[ESTPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESCPRO] [varchar] (80) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDMASC] [int] NOT NULL,
[IDMAR] [int] NOT NULL,
[IDCAT] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED ([CODPRO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_CATEGORIA] FOREIGN KEY ([IDCAT]) REFERENCES [dbo].[CATEGORIA] ([IDCAT])
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_MARCA] FOREIGN KEY ([IDMAR]) REFERENCES [dbo].[MARCA] ([IDMAR])
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_MASCOTA] FOREIGN KEY ([IDMASC]) REFERENCES [dbo].[MASCOTA] ([IDMASC])
GO
